<?php
/**
 * The configuration of simpleSAMLphp core:AttributeReleasePolicy authproc filter
 *
 * @version $Id$
 */
$config = array(
	/*
	 * Configuration when 'config' => TRUE is specified for core:AttributeReleasePolicy.
	 *
	 * `entityID'				: array of OR matched entity IDs. 
	 * `RegistrationAuthority'	: array of OR matched registration authorities.
	 * `EntityCategory'			: array of AND matched entity categories. Use '%or' in list to change behaviour.. 
	 * `attributes'				: array of attributes to release if rule matches. Attributes must be the value
	 *							: generated by other authprocs or retrieved from datasources. The include examples include
	 *							: both the friendlyname and OID representations of the attributes.
	 *		Special Flags		: '%all'       - sends all attributes - equivalent to not using AttributeLimit
	 *							: '%requested' - sends attributes requested within the me
	 *							: '%required'  - sends attributes required by metadata (isRequired="true")
	 * `continue'				: (bool) continue processing rules after match. Defaults to true. Set to false to activate.
	 */

	// A selection of attributes to send by default
	array(
		'attributes' => array(
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
			'eduPersonAffiliation','urn:oid:1.3.6.1.4.1.5923.1.1.1.1',
		)
	),

	// Send all requested attributes (defined in metadata) to example service
	array(
		'entityID' => array('https://attribute-tester.example.org/requested-attrs'),
		'attributes' => array('%requested'), // Anything requested
	),

	// Send all required attributes (defined in metadata) to example service
	array(
		'entityID' => array('https://attribute-tester.example.org/required-attrs'),
		'attributes' => array('%required'), // Honour isRequired="true" metadata attributes
	),

	// Send all generated attributes to example service - equivalent to NOT using AttributeLimit
	array(
		'entityID' => array('https://attribute-tester.example.org/all-attrs'),
		'attributes' => array('%all'), // Everything that the IdP generates or SP receives
	),


	// GÉANT Code of Conduct example configuration
	array(
		'EntityCategory' => array('http://www.geant.net/uri/dataprotection-code-of-conduct/v1'),
		'attributes' => array(
			'%required',
		),
	),


	// SWAMID Attribute Release Example - Static Values
	array(
		'RegistrationAuthority' => array('http://www.swamid.se/'),
		'attributes' => array(
			'o','organizationName','',
			'norEduOrgAcronym','urn:oid:1.3.6.1.4.1.2428.90.1.6',
			'c','countryName','urn:oid:2.5.4.6',
			'co','friendlyCountryName','urn:oid:0.9.2342.19200300.100.1.43',
			'schacHomeOrganization','urn:oid:1.3.6.1.4.1.25178.1.2.9',
		),
	),

	// SWAMID Attribute Release Example - Library Resource
	array(
		'RegistrationAuthority' => array('http://www.swamid.se/'),
		'EntityCategory' => array('http://www.swamid.se/category/library-resource'),
		'attributes' => array(
			'eduPersonEntitlement','urn:oid:1.3.6.1.4.1.5923.1.1.1.7',
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
		),
		'continue' => false, 
	),

	// SWAMID Attribute Release Example - R&E AND NREN Service
	array(
		'RegistrationAuthority' => array('http://www.swamid.se/'),
		'EntityCategory' => array(
			'http://www.swamid.se/category/nren-service',
			'http://www.swamid.se/category/research-and-education',
		),
		'attributes' => array(
			'mail','urn:oid:0.9.2342.19200300.100.1.3',
			'displayName','urn:oid:2.16.840.1.113730.3.1.241',
			'givenName','urn:oid:2.5.4.42',
			'sn','surname','urn:oid:2.5.4.4',
			'eduPersonPrincipalName','urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
			'eduPersonScopedAffiliation','urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
		),
	),

	// SWAMID Attribute Release Example - R&E AND EU Adequate Protection
	array(
		'RegistrationAuthority' => array('http://www.swamid.se/'),
		'EntityCategory' => array(
			'http://www.swamid.se/category/eu-adequate-protection',
			'http://www.swamid.se/category/research-and-education',
		),
		'attributes' => array(
			'mail','urn:oid:0.9.2342.19200300.100.1.3',
			'displayName','urn:oid:2.16.840.1.113730.3.1.241',
			'givenName','urn:oid:2.5.4.42',
			'sn','surname','urn:oid:2.5.4.4',
			'eduPersonPrincipalName','urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
			'eduPersonScopedAffiliation','urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
		),
	),

	// SWAMID Attribute Release Example - R&E AND HEI Service
	array(
		'RegistrationAuthority' => array('http://www.swamid.se/'),
		'EntityCategory' => array(
			'http://www.swamid.se/category/hei-service',
			'http://www.swamid.se/category/research-and-education',
		),
		'attributes' => array(
			'mail','urn:oid:0.9.2342.19200300.100.1.3',
			'displayName','urn:oid:2.16.840.1.113730.3.1.241',
			'givenName','urn:oid:2.5.4.42',
			'sn','surname','urn:oid:2.5.4.4',
			'eduPersonPrincipalName','urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
			'eduPersonScopedAffiliation','urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
		),
	),

	// Release norEduPersonNIN to entities from either of the registration
	// authorities below AND defining the Entity Category
	array(
		'RegistrationAuthority' => array(
			'http://www.swamid.se/',
			'http://feide.no/',
			'http://www.csc.fi/haka',
			'https://www.wayf.dk',
		),
		'EntityCategory' => array(
			'http://www.swamid.se/category/sfs-1993-1153'
		),
		'attributes' => array(
			'norEduPersonNIN','urn:oid:1.3.6.1.4.1.2428.90.1.5'
		),
	),


	// UK Federation Core Attributes
	array(
		'RegistrationAuthority' => array('http://ukfederation.org.uk'),
		'attributes' => array(
			'eduPersonScopedAffiliation','urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
			'eduPersonPrincipalName','urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
			'eduPersonEntitlement','urn:oid:1.3.6.1.4.1.5923.1.1.1.7',
		),
	),

	// Don't send any more attributes to services not registered by UK Federation
	array(
		'RegistrationAuthority' => array('http://www.ukfederation.org.uk/','%not'),
		'continue' => false,
	),


	// REFEDS Research & Scholarship Entity Category
	// InCommon Reseach & Scholarship Entity Category
	array(
		'EntityCategory' => array(
			'http://refeds.org/category/research-and-scholarship',
			'http://id.incommon.org/category/research-and-scholarship',
			'%or'
		),
		'attributes' => array(
			'mail','urn:oid:0.9.2342.19200300.100.1.3',
			'displayName','urn:oid:2.16.840.1.113730.3.1.241',
			'givenName','urn:oid:2.5.4.42',
			'sn','surname','urn:oid:2.5.4.4',
			'eduPersonPrincipalName','urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
			'eduPersonTargetedID','urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
			'eduPersonScopedAffiliation','urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
		),
	),
);
